before_install:
  - sudo apt-get update
  - sudo apt-get install --yes build-essential
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo apt-get install --yes git

  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n tyssue python=3.4
  - source activate tyssue
  - conda install numpy scipy pandas matplotlib nose coverage vispy pip
  - conda install -c https://conda.anaconda.org/osgeo cgal
  - pip install coveralls

install:
  - mkdir build/
  - cd build/
  - cmake -DBoost_INCLUDE_DIR=$HOME/miniconda/envs/tyssue/include/ ..
  - make install

script:
  - cd ../
  - gcc --version
  - make coverage

after_success:
  - coveralls
