name: tyssue
channels:
- defaults
- conda-forge

dependencies:
- python>=3.6
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipywidgets
- pythreejs
- ipyvolume
- vispy