name: tyssue
channels:
- conda-forge

dependencies:
- cmake
- pybind11
- pip
- boost-cpp
- mpfr
- gmp
- cgal
- python>=3.6
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- quantities
- ipython
- ipython_genutils
- ipywidgets
- pythreejs
- ipyvolume
- vispy
- meshio
- zarr
- xarray
- scikit-build-core
