name: tyssue
channels: !!python/tuple
- !!python/unicode
  'defaults'
- !!python/unicode
  'conda-forge'

dependencies:
- python>=3.5
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
# - vispy install from source
- pythreejs