name: tyssue
channels: !!python/tuple
- !!python/unicode
  'defaults'
- !!python/unicode
  'conda-forge'

dependencies:
- python>=3.4
- numpy
- scipy
- matplotlib
- pandas
- pytables
- jupyter
- notebook
- vispy
- pythreejs