package:
  name: tyssue
  version: "0.1"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - vispy
    - pytables

about:
  home: https://github.com/CellModels/tyssue
  license: MPLv2.0
