package:
  name: tyssue
  version: "0.2"

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
about:
  home: https://github.com/DamCB/tyssue
  license: MPLv2.0
